import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.filechooser.FileNameExtensionFilter;

import javax.swing.JTextField;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.JFileChooser;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JPasswordField;

public class LoginWindow extends JFrame {
    private String user;
    private String pass;
    public static JFrame frame = new JFrame("Login");
	private JPanel contentPane;
	private JTextField textField;
	private JPasswordField passwordField;

	
	   /**
     * Creates new form Interface
     */
    public LoginWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

    }

	
	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		frame.setSize(300, 150);
		

		JPanel panel = new JPanel();
		frame.add(panel);
		panel.setLayout(null);

        
        JLabel userLabel = new JLabel("Usuario");
        userLabel.setBounds(10, 10, 80, 25);
        panel.add(userLabel);

        final JTextField userText = new JTextField(20);
        userText.setBounds(100, 10, 160, 25);
        panel.add(userText);

        JLabel passwordLabel = new JLabel("Contraseña");
        passwordLabel.setBounds(10, 40, 80, 25);
        panel.add(passwordLabel);

        final JPasswordField passwordText = new JPasswordField(20);
        passwordText.setBounds(100, 40, 160, 25);
        panel.add(passwordText);

        JButton loginButton = new JButton("Acceso");
        loginButton.setBounds(10, 80, 90, 25);
        panel.add(loginButton);
        loginButton.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                String usuario = userText.getText();
                String pass = passwordText.getText();
                try{
                   // Client client = new Client (usuario, pass);    // se le pasa el nombre de usuario
                   // client.initialize ();
                    
                    frame.setVisible(false);
                    
                    //UserList userList=new UserList();
                    //userList.main(client);
                                                         
                }

                catch (Exception ex)
                {
                    System.out.println ("ERROR: " + ex);
                    ex.printStackTrace (System.out);
                }                                                             
                // display/center the jdialog when the button is pressed               
            } 
        });
        JButton registerButton = new JButton("Registro");
        registerButton.setBounds(160, 80, 90, 25);
        panel.add(registerButton);
        registerButton.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                String usuario = userText.getText();
                String pass = passwordText.getText();
                try{
                	
                   // Client client = new Client (usuario, pass);    // se le pasa el nombre de usuario
                   // client.initialize ();
                    
                    frame.setVisible(false);
                    
                    UserWindow userWindow=new UserWindow();
                    userWindow.main();               
                }
                catch (Exception ex)
                {
                    System.out.println ("ERROR: " + ex);
                    ex.printStackTrace (System.out);
                }             
             // display/center the jdialog when the button is pressed              
            } 
        });


		frame.setVisible(true);
	}

    public void close(){
        
        frame.dispose();
    }
    private void setUser(String user){
        this.user=user;
    }
    private void setPassword(String pass){
        this.pass = pass;
    }
    public String getUser(){
        return user;
    }
    public String getPass(){
        return pass;
    }
	
	/**
	 * Create the frame.
	 */
	/*public LoginWindow() {
		getContentPane().setLayout(null);
		
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 468, 350);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		contentPane.setLayout(null);
		
		JLabel lblUsuario = new JLabel("Usuario");
		lblUsuario.setBounds(113, 74, 46, 14);
		contentPane.add(lblUsuario);
		
		textField = new JTextField();
		textField.setBounds(207, 71, 86, 20);
		contentPane.add(textField);
		textField.setColumns(10);
		
		JLabel lblContrasea = new JLabel("Contrase\u00F1a");
		lblContrasea.setBounds(113, 121, 63, 14);
		contentPane.add(lblContrasea);
		
		passwordField = new JPasswordField();
		passwordField.setBounds(207, 118, 86, 20);
		contentPane.add(passwordField);
		
		JButton btnAcceder = new JButton("Acceder");
		btnAcceder.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				
			}
		});
		btnAcceder.setBounds(158, 171, 89, 23);
		contentPane.add(btnAcceder);
		
		JButton btnRegistro = new JButton("Registro");
		btnRegistro.setBounds(158, 217, 89, 23);
		contentPane.add(btnRegistro);
		
		
		*/
		//contentPane.add(btnBoton);
				
		/*JFileChooser chooser = new JFileChooser();
	    FileNameExtensionFilter filter = new FileNameExtensionFilter(
	        "JPG & GIF Images", "jpg", "gif");
	    chooser.setFileFilter(filter);
	    int returnVal = chooser.showOpenDialog(contentPane);
	    if(returnVal == JFileChooser.APPROVE_OPTION) {
	       System.out.println("You chose to open this file: " +
	            chooser.getSelectedFile().getName());
	    }*/

	  //  contentPane.add(chooser);
	//}
}
