import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.JFrame;

public class UserWindow extends JPanel {
    public JFrame frame = new JFrame("Lista de Usuarios");

	
	
  public UserWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        private void initComponents() {

    }
	/**
	 * Create the panel.
	 */
    public void main() throws Exception {
        frame.setSize(300, 300);
        JPanel panel = new JPanel();
		frame.add(panel);
		panel.setLayout(null);
		
		JLabel lblHola = new JLabel("HOLA");
		lblHola.setBounds(25, 90, 27, 14);
		panel.add(lblHola);

		JButton btnBoton = new JButton("Boton");
		btnBoton.setBounds(77, 86, 89, 23);
		panel.add(btnBoton);

		
		frame.setVisible(true);

	}
}
